stages:
  - run

run_expense_tracker:
  stage: run
  image: python:3.11
  script:
    - pip install --upgrade pip
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi
    - python src/main.py
  artifacts:
    paths:
      - results/
    expire_in: 1 week
